### 
POST http://localhost:3333/livro
Content-Type: application/json

{
"endereco": "Rua das Flores, 123",
"tipo": "Apartamento",
"area": 80,
"valor": 450000
}

###

GET http://localhost:3333/imoveis


### 
GET http://localhost:3333/imoveis?search=Apartamento

### 
PUT http://localhost:3333/imoveis/4608c62e-ca24-4429-a559-e8d571b85f4e
Content-Type: application/json

{
"endereco": "Rua Nova, 456",
"tipo": "Casa",
"area": 120,
"valor": 600000
}

###
PATCH http://localhost:3333/imoveis/15694dd9-a966-499d-8497-60b0a3d46fcc
Content-Type: application/json

{
"area": 90,
"valor": 470000
}


###

DELETE http://localhost:3333/imoveis/ecdba636-9797-452a-8151-95134de1919e
